import js from "@eslint/js";

export default [
    js.configs.recommended,
    {
        languageOptions: {
            ecmaVersion: "latest",
            sourceType: "module",
            globals: {
                console: "readonly",
                process: "readonly",
                Buffer: "readonly",
                __dirname: "readonly",
                __filename: "readonly",
                global: "readonly",
                module: "readonly",
                require: "readonly",
                exports: "readonly",
                setTimeout: "readonly",
                clearTimeout: "readonly",
                setInterval: "readonly",
                clearInterval: "readonly",
                fetch: "readonly",
            },
        },
        rules: {
            "indent": ["error", 4],
            "linebreak-style": ["error", "unix"],
            "quotes": ["error", "double"],
            "semi": ["error", "always"],
            "no-unused-vars": ["error", { "argsIgnorePattern": "^_", "caughtErrorsIgnorePattern": "^_" }],
            "no-console": "warn",
            "no-debugger": "error",
            "prefer-const": "error",
            "no-var": "error",
            "arrow-spacing": "error",
            "comma-dangle": ["error", "always-multiline"],
            "comma-spacing": "error",
            "key-spacing": "error",
            "keyword-spacing": "error",
            "object-curly-spacing": ["error", "always"],
            "space-before-blocks": "error",
            "space-in-parens": ["error", "never"],
            "no-trailing-spaces": "error",
            "eol-last": "error",
            "max-len": ["warn", { "code": 120 }],
            "camelcase": ["error", { "properties": "never" }],
            "no-multiple-empty-lines": ["error", { "max": 2 }],
            "padded-blocks": ["error", "never"],
        },
        ignores: [
            "node_modules/",
            "dist/",
            "build/",
            "coverage/",
            "**/*.test.js",
            "**/__tests__/**",
        ],
    },
];